services:
  postgres:
    image: postgres:15-alpine
    container_name: lang_courses_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-lang_courses}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      
    # TODO: ПРОВЕРИТЬ
    # Было в ветке main
    # ports:
    #   - "5432:5432"
    networks:
      - lang_courses_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5

  admin:
    build:
      context: .
      dockerfile: Dockerfile.admin
    container_name: lang_courses_admin
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: production
      PORT: 3001
      DATABASE_URL: postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@postgres:5432/${POSTGRES_DB:-lang_courses}
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - lang_courses_network

  bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    container_name: lang_courses_bot
    restart: unless-stopped
    environment:
      PYTHONUNBUFFERED: 1
      PYTHONPATH: /app:/app/bot
      DATABASE_URL: postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@postgres:5432/${POSTGRES_DB:-lang_courses}
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./logs:/app/logs
      - whisper_cache:/root/.cache/huggingface
    networks:
      - lang_courses_network
    deploy:
      resources:
        limits:
          cpus: '0.8'
          memory: 2G
        reservations:
          memory: 1G
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: lang_courses_api
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      PYTHONUNBUFFERED: 1
      PYTHONPATH: /app:/app/bot
      DATABASE_URL: postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@postgres:5432/${POSTGRES_DB:-lang_courses}
      TELEGRAM_BOT_TOKEN: ${BOT_TOKEN}
      WEBHOOK_API_KEY: ${WEBHOOK_API_KEY}
   
      BOT_WEBHOOK_URL: http://api:8000/webhook

    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - lang_courses_network

networks:
  lang_courses_network:
    driver: bridge

volumes:
  postgres_data:
  whisper_cache:
